version: '3.8'
services:
  booksDocker:
    profiles: [ "docker" ]
    container_name: booksDocker
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_EUREKA_URL=eurekaDocker
    image: kevinsantiagorey/unir_books:v.0.2
    ports:
      - "8082:8082"
    networks:
      - eureka_unir_books
    depends_on:
      - db
      - pgadmin


networks:
  eureka_unir_books:
    driver: bridge