eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9191

tracing:
  url: http://localhost:4318/v1/traces

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://BOOKS
          predicates:
            - Path=/api/v1/books/**
        - id: ORDER-SERVICE
          uri: lb://REQUESTS
          predicates:
            - Path=/api/v1/requests/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - ${ALLOWED_ORIGINS:*}
            allowed-headers:
              - "*"
            allowed-methods:
              - POST