server:
  port: 8082

spring:
  application:
    name: books
  datasource:
    password: admin
    url: jdbc:postgresql://localhost:5432/books?sslmode=require
    username: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  data:
    elasticsearch:
      repositories:
        enabled: true
        cluster-nodes: localhost:9200
        cluster-name: docker-cluster

tracing:
  url: http://localhost:4318/v1/traces

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

